apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: game-backend
  labels:
    app: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.6-bionic
          env:
            - name: MONGO_INITDB_DATABASE
              value: gameMaster
          ports:
            - name: mongo
              containerPort: 27017
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 384Mi
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongo


