apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: game-backend
  labels:
    app: mongo
spec:
  selector:
    label: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
      protocol: TCP
